
import type { Product } from '@/lib/types';

const NEW_IMAGE_URL = 'https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Intricate Mandala Wall Art',
    description: 'Hand-painted wooden mandala, perfect for adding a spiritual and artistic touch to your living space. Each piece is unique.',
    careInstructions: 'Wipe clean with a soft, dry cloth. Avoid direct sunlight and moisture.',
    imageUrl: NEW_IMAGE_URL,
    dataAiHint: 'mandala art',
    price: '₹2,499',
    category: 'Wall Art',
    isLatest: true,
    sizeAndDimensions: 'Diameter: 24 inches (60 cm), Thickness: 0.5 inches (1.25 cm)',
    material: 'Sustainable Mango Wood, Non-toxic Acrylic Paints',
    reviews: [
      { reviewer: 'Priya S.', rating: 5, comment: 'Absolutely stunning! Even more beautiful in person. Quality is top-notch.', date: '2024-07-15' },
      { reviewer: 'Amit K.', rating: 4, comment: 'Great addition to my meditation room. Colors are vibrant.', date: '2024-07-10' },
    ],
  },
  {
    id: '2',
    name: 'Elegant Ceramic Vase Set',
    description: 'Set of three minimalist ceramic vases in earthy tones, ideal for modern and traditional decor. Perfect for dried flowers or as standalone pieces.',
    careInstructions: 'Hand wash only with mild soap. Handle with care to avoid chipping.',
    imageUrl: NEW_IMAGE_URL,
    dataAiHint: 'ceramic vase',
    price: '₹1,899',
    category: 'Tabletops',
    isLatest: true,
    sizeAndDimensions: 'Small: 4" H x 3" D, Medium: 6" H x 3.5" D, Large: 8" H x 4" D',
    material: 'High-fired Stoneware Ceramic, Matte Glaze',
    reviews: [
      { reviewer: 'Neha B.', rating: 5, comment: 'These vases are so chic and versatile. Love the texture.', date: '2024-07-12' },
    ],
  },
  {
    id: '3',
    name: 'Bohemian Tasseled Mirror',
    description: 'A stunning statement piece mirror framed with natural fibers and cotton tassels, adding a touch of boho chic to any room.',
    careInstructions: 'Clean mirror surface with glass cleaner. Dust tassels gently or use a low-suction vacuum attachment.',
    imageUrl: NEW_IMAGE_URL,
    dataAiHint: 'boho mirror',
    price: '₹3,200',
    category: 'Mirrors',
    isLatest: true,
    sizeAndDimensions: 'Overall Diameter: 30 inches (76 cm), Mirror Diameter: 18 inches (45 cm)',
    material: 'Natural Jute, Cotton Tassels, Glass Mirror, Wooden Frame',
    reviews: [
      { reviewer: 'Rohan M.', rating: 5, comment: 'Fantastic mirror, really transforms the space. Well made.', date: '2024-07-05' },
      { reviewer: 'Sunita P.', rating: 4, comment: 'Love the boho vibe! Tassels are a bit delicate.', date: '2024-07-01' },
    ],
  },
  {
    id: '4',
    name: 'Artisan-Crafted Table Runner',
    description: 'Hand-woven cotton table runner featuring traditional motifs and rich textures. Brings heritage and warmth to your dining experience.',
    careInstructions: 'Gentle hand wash or dry clean recommended. Iron on low heat on the reverse side.',
    imageUrl: NEW_IMAGE_URL,
    dataAiHint: 'table runner',
    price: '₹1,550',
    category: 'Textiles',
    sizeAndDimensions: 'Length: 72 inches (183 cm), Width: 14 inches (35 cm)',
    material: '100% Handloom Cotton, Natural Dyes',
    reviews: [
      { reviewer: 'Kavita J.', rating: 5, comment: 'Beautiful craftsmanship and vibrant colors. Perfect for my dining table.', date: '2024-06-28' },
    ],
  },
  {
    id: '5',
    name: 'Handcrafted Wooden Bowl',
    description: 'A versatile and beautiful wooden bowl, hand-carved by skilled artisans. Ideal for serving or as a decorative centerpiece.',
    careInstructions: 'Wipe with a damp cloth. Occasionally treat with food-safe mineral oil.',
    imageUrl: NEW_IMAGE_URL,
    dataAiHint: 'wooden bowl',
    price: '₹1,250',
    category: 'Tabletops',
    sizeAndDimensions: 'Diameter: 10 inches (25 cm), Height: 3 inches (7.5 cm)',
    material: 'Acacia Wood, Food-safe Polish',
    reviews: [], // No reviews yet
  },
  {
    id: '6',
    name: 'Expressive Abstract Canvas Art',
    description: 'Vibrant and expressive abstract art on canvas, ready to hang. Adds a contemporary flair and a pop of color to your walls.',
    careInstructions: 'Dust gently with a feather duster. Avoid placing in humid areas.',
    imageUrl: NEW_IMAGE_URL,
    dataAiHint: 'abstract art',
    price: '₹4,500',
    category: 'Wall Art',
    sizeAndDimensions: 'Width: 36 inches (91 cm), Height: 24 inches (60 cm)',
    material: 'Acrylic on Canvas, Pine Wood Stretcher Bars',
    reviews: [
      { reviewer: 'Vikram R.', rating: 4, comment: 'Adds a nice pop of color to my living room. Good quality print.', date: '2024-06-15' },
    ],
  },
  {
    id: '7',
    name: 'Macrame Plant Hanger',
    description: 'Stylish macrame plant hanger, perfect for bringing greenery indoors. Fits various pot sizes.',
    careInstructions: 'Spot clean with a damp cloth. Keep away from direct flame.',
    imageUrl: NEW_IMAGE_URL,
    dataAiHint: 'macrame plant',
    price: '₹899',
    category: 'Planters',
    sizeAndDimensions: 'Length: 35 inches (89 cm), Fits pots up to 8 inches diameter',
    material: '100% Cotton Cord, Wooden Ring',
    reviews: [
      { reviewer: 'Anjali G.', rating: 5, comment: 'Very sturdy and looks great with my pothos!', date: '2024-07-18' },
    ],
  },
  {
    id: '8',
    name: 'Ethnic Print Cushion Covers',
    description: 'Set of two vibrant cushion covers with traditional ethnic prints. Adds color and comfort to your sofa or bed.',
    careInstructions: 'Machine wash cold, gentle cycle. Tumble dry low.',
    imageUrl: NEW_IMAGE_URL,
    dataAiHint: 'cushion covers',
    price: '₹1,299',
    category: 'Textiles',
    sizeAndDimensions: '16x16 inches (40x40 cm) per cover',
    material: 'Cotton Blend Fabric, Hidden Zipper Closure',
    reviews: [
      { reviewer: 'Rajesh V.', rating: 4, comment: 'Good quality fabric and print. Colors are true to picture.', date: '2024-07-20' },
      { reviewer: 'Smita L.', rating: 5, comment: 'Brightened up my couch instantly. Love them!', date: '2024-07-19' },
    ],
  },
];
